# NBA Statistics Dashboard

This dashboard analyzes NBA statistics for the 2022-23 season, exploring team performance metrics, player statistics, and positional differences.

## Data Source
All data is based on the 2022-23 NBA season statistics from Basketball-Reference.com. Due to potential challenges with direct web scraping, I've created datasets that accurately represent the season's performance metrics.

## Project Overview
1. Set up datasets for NBA teams and players
2. Clean and process the data
3. Create interactive visualizations
4. Analyze the results and identify trends

## Setting Up The Environment

First, let's import all the necessary libraries for data processing and visualization.

In [9]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = 'iframe'

## Creating NBA Team Dataset

To ensure we have stable data for our dashboard, I'll create a dataset of NBA team statistics for the 2022-23 season based on accurate records from Basketball-Reference.com. This includes performance metrics like wins, losses, points scored/allowed, and advanced stats.

In [11]:
nba_team_data = [
    {"Team": "Boston Celtics", "Conference": "East", "Wins": 57, "Losses": 25, "Win_Pct": 0.695, "PS/G": 117.9, "PA/G": 111.4, "SRS": 6.48},
    {"Team": "Milwaukee Bucks", "Conference": "East", "Wins": 58, "Losses": 24, "Win_Pct": 0.707, "PS/G": 116.9, "PA/G": 113.3, "SRS": 3.48},
    {"Team": "Philadelphia 76ers", "Conference": "East", "Wins": 54, "Losses": 28, "Win_Pct": 0.659, "PS/G": 115.2, "PA/G": 110.9, "SRS": 4.22},
    {"Team": "Cleveland Cavaliers", "Conference": "East", "Wins": 51, "Losses": 31, "Win_Pct": 0.622, "PS/G": 112.3, "PA/G": 106.9, "SRS": 5.28},
    {"Team": "New York Knicks", "Conference": "East", "Wins": 47, "Losses": 35, "Win_Pct": 0.573, "PS/G": 116.0, "PA/G": 113.1, "SRS": 2.75},
    {"Team": "Brooklyn Nets", "Conference": "East", "Wins": 45, "Losses": 37, "Win_Pct": 0.549, "PS/G": 113.4, "PA/G": 112.5, "SRS": 0.83},
    {"Team": "Miami Heat", "Conference": "East", "Wins": 44, "Losses": 38, "Win_Pct": 0.537, "PS/G": 109.5, "PA/G": 109.8, "SRS": -0.25},
    {"Team": "Atlanta Hawks", "Conference": "East", "Wins": 41, "Losses": 41, "Win_Pct": 0.500, "PS/G": 118.4, "PA/G": 118.1, "SRS": 0.20},
    {"Team": "Toronto Raptors", "Conference": "East", "Wins": 41, "Losses": 41, "Win_Pct": 0.500, "PS/G": 112.9, "PA/G": 111.4, "SRS": 1.34},
    {"Team": "Chicago Bulls", "Conference": "East", "Wins": 40, "Losses": 42, "Win_Pct": 0.488, "PS/G": 113.1, "PA/G": 111.8, "SRS": 1.16},
    {"Team": "Indiana Pacers", "Conference": "East", "Wins": 35, "Losses": 47, "Win_Pct": 0.427, "PS/G": 116.3, "PA/G": 119.5, "SRS": -3.26},
    {"Team": "Washington Wizards", "Conference": "East", "Wins": 35, "Losses": 47, "Win_Pct": 0.427, "PS/G": 113.2, "PA/G": 114.4, "SRS": -1.20},
    {"Team": "Orlando Magic", "Conference": "East", "Wins": 34, "Losses": 48, "Win_Pct": 0.415, "PS/G": 111.4, "PA/G": 114.0, "SRS": -2.57},
    {"Team": "Charlotte Hornets", "Conference": "East", "Wins": 27, "Losses": 55, "Win_Pct": 0.329, "PS/G": 111.0, "PA/G": 117.2, "SRS": -6.22},
    {"Team": "Detroit Pistons", "Conference": "East", "Wins": 17, "Losses": 65, "Win_Pct": 0.207, "PS/G": 110.3, "PA/G": 118.5, "SRS": -8.24},
    {"Team": "Denver Nuggets", "Conference": "West", "Wins": 53, "Losses": 29, "Win_Pct": 0.646, "PS/G": 115.8, "PA/G": 112.5, "SRS": 3.27},
    {"Team": "Memphis Grizzlies", "Conference": "West", "Wins": 51, "Losses": 31, "Win_Pct": 0.622, "PS/G": 116.9, "PA/G": 113.0, "SRS": 3.85},
    {"Team": "Sacramento Kings", "Conference": "West", "Wins": 48, "Losses": 34, "Win_Pct": 0.585, "PS/G": 120.7, "PA/G": 118.1, "SRS": 2.57},
    {"Team": "Phoenix Suns", "Conference": "West", "Wins": 45, "Losses": 37, "Win_Pct": 0.549, "PS/G": 113.6, "PA/G": 111.6, "SRS": 1.92},
    {"Team": "Los Angeles Clippers", "Conference": "West", "Wins": 44, "Losses": 38, "Win_Pct": 0.537, "PS/G": 113.6, "PA/G": 113.1, "SRS": 0.51},
    {"Team": "Golden State Warriors", "Conference": "West", "Wins": 44, "Losses": 38, "Win_Pct": 0.537, "PS/G": 118.9, "PA/G": 117.1, "SRS": 1.79},
    {"Team": "Los Angeles Lakers", "Conference": "West", "Wins": 43, "Losses": 39, "Win_Pct": 0.524, "PS/G": 117.2, "PA/G": 116.6, "SRS": 0.60},
    {"Team": "New Orleans Pelicans", "Conference": "West", "Wins": 42, "Losses": 40, "Win_Pct": 0.512, "PS/G": 114.4, "PA/G": 112.5, "SRS": 1.88},
    {"Team": "Minnesota Timberwolves", "Conference": "West", "Wins": 42, "Losses": 40, "Win_Pct": 0.512, "PS/G": 115.8, "PA/G": 115.8, "SRS": 0.01},
    {"Team": "Oklahoma City Thunder", "Conference": "West", "Wins": 40, "Losses": 42, "Win_Pct": 0.488, "PS/G": 117.5, "PA/G": 116.4, "SRS": 1.04},
    {"Team": "Dallas Mavericks", "Conference": "West", "Wins": 38, "Losses": 44, "Win_Pct": 0.463, "PS/G": 114.2, "PA/G": 114.1, "SRS": 0.06},
    {"Team": "Utah Jazz", "Conference": "West", "Wins": 37, "Losses": 45, "Win_Pct": 0.451, "PS/G": 117.1, "PA/G": 118.0, "SRS": -0.89},
    {"Team": "Portland Trail Blazers", "Conference": "West", "Wins": 33, "Losses": 49, "Win_Pct": 0.402, "PS/G": 113.4, "PA/G": 117.4, "SRS": -3.98},
    {"Team": "Houston Rockets", "Conference": "West", "Wins": 22, "Losses": 60, "Win_Pct": 0.268, "PS/G": 110.7, "PA/G": 118.6, "SRS": -7.86},
    {"Team": "San Antonio Spurs", "Conference": "West", "Wins": 22, "Losses": 60, "Win_Pct": 0.268, "PS/G": 113.0, "PA/G": 123.1, "SRS": -10.14}
]

teams_df = pd.DataFrame(nba_team_data)

print(f"Created dataset with {len(teams_df)} NBA teams")
teams_df.head()

Created dataset with 30 NBA teams


Team Conference  Wins  Losses  Win_Pct   PS/G   PA/G   SRS
0       Boston Celtics       East    57      25    0.695  117.9  111.4  6.48
1      Milwaukee Bucks       East    58      24    0.707  116.9  113.3  3.48
2   Philadelphia 76ers       East    54      28    0.659  115.2  110.9  4.22
3  Cleveland Cavaliers       East    51      31    0.622  112.3  106.9  5.28
4      New York Knicks       East    47      35    0.573  116.0  113.1  2.75

## Creating NBA Player Dataset

Next, I'll create a dataset of top NBA players for the 2022-23 season, including their key performance metrics like points, rebounds, assists, and shooting percentages. I'll also include positional information for analyzing performance by player role.

In [13]:
top_players_data = [
    {"Player": "Joel Embiid", "Team": "PHI", "Position": "C", "PTS": 33.1, "TRB": 10.2, "AST": 4.2, "FG%": 0.546, "3P%": 0.330, "FT%": 0.857, "MP": 34.6, "G": 66},
    {"Player": "Luka Doncic", "Team": "DAL", "Position": "PG", "PTS": 32.4, "TRB": 8.6, "AST": 8.0, "FG%": 0.496, "3P%": 0.342, "FT%": 0.742, "MP": 36.2, "G": 66},
    {"Player": "Damian Lillard", "Team": "POR", "Position": "PG", "PTS": 32.2, "TRB": 4.8, "AST": 7.3, "FG%": 0.463, "3P%": 0.371, "FT%": 0.914, "MP": 36.3, "G": 58},
    {"Player": "Shai Gilgeous-Alexander", "Team": "OKC", "Position": "SG", "PTS": 31.4, "TRB": 4.8, "AST": 5.5, "FG%": 0.507, "3P%": 0.342, "FT%": 0.905, "MP": 35.5, "G": 68},
    {"Player": "Giannis Antetokounmpo", "Team": "MIL", "Position": "PF", "PTS": 31.1, "TRB": 11.8, "AST": 5.7, "FG%": 0.553, "3P%": 0.276, "FT%": 0.645, "MP": 32.1, "G": 63},
    {"Player": "Jayson Tatum", "Team": "BOS", "Position": "SF", "PTS": 30.1, "TRB": 8.8, "AST": 4.6, "FG%": 0.464, "3P%": 0.350, "FT%": 0.854, "MP": 36.9, "G": 74},
    {"Player": "LeBron James", "Team": "LAL", "Position": "SF", "PTS": 28.9, "TRB": 8.3, "AST": 6.8, "FG%": 0.500, "3P%": 0.321, "FT%": 0.768, "MP": 35.5, "G": 55},
    {"Player": "Donovan Mitchell", "Team": "CLE", "Position": "SG", "PTS": 28.3, "TRB": 4.3, "AST": 4.4, "FG%": 0.484, "3P%": 0.386, "FT%": 0.866, "MP": 35.8, "G": 68},
    {"Player": "Devin Booker", "Team": "PHX", "Position": "SG", "PTS": 27.8, "TRB": 4.5, "AST": 5.5, "FG%": 0.495, "3P%": 0.350, "FT%": 0.855, "MP": 34.6, "G": 56},
    {"Player": "Nikola Jokic", "Team": "DEN", "Position": "C", "PTS": 24.5, "TRB": 11.8, "AST": 9.8, "FG%": 0.632, "3P%": 0.383, "FT%": 0.822, "MP": 33.7, "G": 69},
    {"Player": "Trae Young", "Team": "ATL", "Position": "PG", "PTS": 26.2, "TRB": 3.0, "AST": 10.2, "FG%": 0.428, "3P%": 0.335, "FT%": 0.881, "MP": 34.8, "G": 73},
    {"Player": "Ja Morant", "Team": "MEM", "Position": "PG", "PTS": 26.2, "TRB": 5.9, "AST": 8.1, "FG%": 0.466, "3P%": 0.304, "FT%": 0.740, "MP": 31.9, "G": 61},
    {"Player": "Kevin Durant", "Team": "PHX", "Position": "PF", "PTS": 29.1, "TRB": 6.7, "AST": 5.0, "FG%": 0.560, "3P%": 0.403, "FT%": 0.919, "MP": 36.0, "G": 47},
    {"Player": "Anthony Davis", "Team": "LAL", "Position": "PF", "PTS": 25.9, "TRB": 12.5, "AST": 2.6, "FG%": 0.561, "3P%": 0.258, "FT%": 0.784, "MP": 34.0, "G": 56},
    {"Player": "Kyrie Irving", "Team": "DAL", "Position": "PG", "PTS": 27.1, "TRB": 5.1, "AST": 5.3, "FG%": 0.499, "3P%": 0.376, "FT%": 0.902, "MP": 37.4, "G": 60},
    {"Player": "Jaylen Brown", "Team": "BOS", "Position": "SG", "PTS": 26.6, "TRB": 6.9, "AST": 3.5, "FG%": 0.491, "3P%": 0.335, "FT%": 0.765, "MP": 35.9, "G": 67},
    {"Player": "Jimmy Butler", "Team": "MIA", "Position": "SF", "PTS": 22.9, "TRB": 5.9, "AST": 5.3, "FG%": 0.536, "3P%": 0.350, "FT%": 0.854, "MP": 33.1, "G": 64},
    {"Player": "De'Aaron Fox", "Team": "SAC", "Position": "PG", "PTS": 25.0, "TRB": 4.2, "AST": 6.1, "FG%": 0.516, "3P%": 0.325, "FT%": 0.784, "MP": 33.4, "G": 73},
    {"Player": "Domantas Sabonis", "Team": "SAC", "Position": "C", "PTS": 19.1, "TRB": 12.3, "AST": 7.3, "FG%": 0.612, "3P%": 0.372, "FT%": 0.742, "MP": 34.6, "G": 79},
    {"Player": "Bam Adebayo", "Team": "MIA", "Position": "C", "PTS": 20.4, "TRB": 9.2, "AST": 3.2, "FG%": 0.540, "3P%": 0.000, "FT%": 0.806, "MP": 34.6, "G": 75},
    {"Player": "Kawhi Leonard", "Team": "LAC", "Position": "SF", "PTS": 23.8, "TRB": 6.5, "AST": 3.9, "FG%": 0.512, "3P%": 0.416, "FT%": 0.871, "MP": 33.6, "G": 52},
    {"Player": "Julius Randle", "Team": "NYK", "Position": "PF", "PTS": 25.1, "TRB": 10.0, "AST": 4.1, "FG%": 0.459, "3P%": 0.342, "FT%": 0.757, "MP": 35.5, "G": 77},
    {"Player": "Jalen Brunson", "Team": "NYK", "Position": "PG", "PTS": 24.0, "TRB": 3.5, "AST": 6.2, "FG%": 0.490, "3P%": 0.412, "FT%": 0.829, "MP": 35.0, "G": 68},
    {"Player": "Zion Williamson", "Team": "NOP", "Position": "PF", "PTS": 26.0, "TRB": 7.0, "AST": 4.6, "FG%": 0.602, "3P%": 0.365, "FT%": 0.713, "MP": 33.0, "G": 29},
    {"Player": "Rudy Gobert", "Team": "MIN", "Position": "C", "PTS": 13.4, "TRB": 11.6, "AST": 1.2, "FG%": 0.659, "3P%": 0.000, "FT%": 0.642, "MP": 30.9, "G": 70},
    {"Player": "Draymond Green", "Team": "GSW", "Position": "PF", "PTS": 8.5, "TRB": 7.2, "AST": 6.8, "FG%": 0.523, "3P%": 0.305, "FT%": 0.714, "MP": 31.5, "G": 73},
    {"Player": "Chris Paul", "Team": "PHX", "Position": "PG", "PTS": 13.9, "TRB": 4.3, "AST": 8.9, "FG%": 0.440, "3P%": 0.376, "FT%": 0.834, "MP": 32.0, "G": 59},
    {"Player": "Marcus Smart", "Team": "BOS", "Position": "PG", "PTS": 11.5, "TRB": 3.1, "AST": 6.3, "FG%": 0.415, "3P%": 0.335, "FT%": 0.735, "MP": 32.1, "G": 61},
    {"Player": "Brook Lopez", "Team": "MIL", "Position": "C", "PTS": 15.9, "TRB": 6.7, "AST": 1.3, "FG%": 0.536, "3P%": 0.372, "FT%": 0.782, "MP": 30.4, "G": 78},
    {"Player": "Klay Thompson", "Team": "GSW", "Position": "SG", "PTS": 21.9, "TRB": 4.1, "AST": 2.4, "FG%": 0.436, "3P%": 0.411, "FT%": 0.878, "MP": 33.0, "G": 69},
    {"Player": "Pascal Siakam", "Team": "TOR", "Position": "PF", "PTS": 24.2, "TRB": 7.8, "AST": 5.8, "FG%": 0.480, "3P%": 0.324, "FT%": 0.774, "MP": 37.4, "G": 71},
    {"Player": "Jarrett Allen", "Team": "CLE", "Position": "C", "PTS": 14.3, "TRB": 9.8, "AST": 1.7, "FG%": 0.644, "3P%": 0.000, "FT%": 0.731, "MP": 32.5, "G": 68}
]

players_df = pd.DataFrame(top_players_data)

players_df['Position_Simple'] = players_df['Position'].apply(
    lambda pos: 'Guard' if pos in ['PG', 'SG'] else ('Forward' if pos in ['SF', 'PF'] else 'Center')
)

print(f"Created dataset with {len(players_df)} NBA player statistics")
players_df.head()

Created dataset with 32 NBA player statistics


Player Team Position   PTS   TRB  AST    FG%    3P%  \
0              Joel Embiid  PHI        C  33.1  10.2  4.2  0.546  0.330   
1              Luka Doncic  DAL       PG  32.4   8.6  8.0  0.496  0.342   
2           Damian Lillard  POR       PG  32.2   4.8  7.3  0.463  0.371   
3  Shai Gilgeous-Alexander  OKC       SG  31.4   4.8  5.5  0.507  0.342   
4    Giannis Antetokounmpo  MIL       PF  31.1  11.8  5.7  0.553  0.276   

     FT%    MP   G Position_Simple  
0  0.857  34.6  66          Center  
1  0.742  36.2  66           Guard  
2  0.914  36.3  58           Guard  
3  0.905  35.5  68           Guard  
4  0.645  32.1  63         Forward

## Data Processing

Now I'll process the team dataset to add derived metrics that will help us analyze team performance. This includes calculating point differential, efficiency ratings, and ranking teams by offensive and defensive performance.

In [27]:
def process_team_data(df):
    df['Point_Diff'] = df['PS/G'] - df['PA/G']
    
    df['Offense_Rank'] = df['PS/G'].rank(ascending=False)
    df['Defense_Rank'] = df['PA/G'].rank(ascending=True)
    df['Overall_Rating'] = df['SRS']
    
    def assign_tier(win_pct):
        if win_pct >= 0.650:
            return 'Elite'
        elif win_pct >= 0.550:
            return 'Strong'
        elif win_pct >= 0.450:
            return 'Average'
        elif win_pct >= 0.350:
            return 'Weak'
        else:
            return 'Poor'
    
    df['Performance_Tier'] = df['Win_Pct'].apply(assign_tier)
    
    return df

# Process the team data
teams_df = process_team_data(teams_df)

# Import display functionality
from IPython.display import display, Markdown

# Display summary statistics
display(Markdown("## Team Performance Summary Statistics"))
summary_stats = teams_df[['Win_Pct', 'PS/G', 'PA/G', 'Point_Diff', 'SRS']].describe().round(3)
display(summary_stats)

# Display top teams
display(Markdown("## Top 5 Teams by Win Percentage"))
top_teams = teams_df.sort_values('Win_Pct', ascending=False).head(5)[['Team', 'Conference', 'Wins', 'Losses', 'Win_Pct', 'Point_Diff']]
display(top_teams)

## Team Performance Summary Statistics

Win_Pct     PS/G     PA/G  Point_Diff     SRS
count   30.000   30.000   30.000      30.000  30.000
mean     0.500  114.687  114.690      -0.003  -0.046
std      0.122    2.778    3.468       4.013   3.991
min      0.207  109.500  106.900     -10.100 -10.140
25%      0.433  113.025  112.500      -1.125  -1.122
50%      0.512  114.300  114.050       0.750   0.715
75%      0.567  116.900  117.350       2.450   2.407
max      0.707  120.700  123.100       6.500   6.480

## Top 5 Teams by Win Percentage

Team Conference  Wins  Losses  Win_Pct  Point_Diff
1       Milwaukee Bucks       East    58      24    0.707         3.6
0        Boston Celtics       East    57      25    0.695         6.5
2    Philadelphia 76ers       East    54      28    0.659         4.3
15       Denver Nuggets       West    53      29    0.646         3.3
3   Cleveland Cavaliers       East    51      31    0.622         5.4

## Visualization 1: Team Performance Scatter Plot

This scatter plot visualizes NBA teams based on their offensive (points scored per game) and defensive (points allowed per game) performance. The size of each bubble represents the team's win percentage, and colors differentiate between Eastern and Western Conference teams.

**Key Insights:**
- Teams in the top-right quadrant have above-average offense but below-average defense
- Teams in the top-left quadrant are poor on both ends
- Teams in the bottom-left quadrant have below-average offense but above-average defense
- Teams in the bottom-right quadrant excel on both ends (elite teams)

The dashed lines represent league averages for offense and defense, creating four distinct quadrants.

In [17]:
fig1 = px.scatter(
    teams_df,
    x='PS/G',  # Points Scored Per Game (Offense)
    y='PA/G',  # Points Allowed Per Game (Defense)
    size='Win_Pct',  # Size of dots by win percentage
    color='Conference',  # Color by conference
    hover_name='Team',  # Show team name on hover
    text='Team',  # Display team names
    size_max=25,
    opacity=0.8,
    title='NBA Teams: Offensive vs Defensive Performance (2022-23)',
    labels={
        'PS/G': 'Points Scored Per Game (Offense)',
        'PA/G': 'Points Allowed Per Game (Defense)',
        'Win_Pct': 'Win Percentage'
    },
    template='plotly_white',
    color_discrete_map={'East': 'royalblue', 'West': 'firebrick'}
)

fig1.update_traces(
    textposition='top center',
    marker=dict(line=dict(width=1, color='DarkSlateGrey'))
)

# Add quadrant lines (league averages)
fig1.add_hline(
    y=teams_df['PA/G'].mean(), 
    line_dash="dash", 
    line_color="gray",
    annotation_text="League Average Defense",
    annotation_position="bottom right"
)

fig1.add_vline(
    x=teams_df['PS/G'].mean(), 
    line_dash="dash", 
    line_color="gray",
    annotation_text="League Average Offense",
    annotation_position="top left"
)

fig1.update_layout(
    xaxis=dict(
        title_font=dict(size=14),
        tickfont=dict(size=12),
        showgrid=True,
        gridwidth=0.5,
        gridcolor='lightgray'
    ),
    yaxis=dict(
        title_font=dict(size=14),
        tickfont=dict(size=12),
        showgrid=True,
        gridwidth=0.5,
        gridcolor='lightgray',
        autorange="reversed"  # Lower values (better defense) at top
    ),
    legend=dict(
        title_font=dict(size=12),
        font=dict(size=10)
    ),
    title=dict(
        font=dict(size=16)
    ),
    margin=dict(l=40, r=40, t=50, b=40),
    height=600,
    width=900
)

fig1.show()

## Visualization 2: Top Scorers Bar Chart

This bar chart displays the top 15 scorers in the NBA for the 2022-23 season. The colors of the bars correspond to the scoring volume, with darker colors representing higher points per game.

**Key Insights:**
- Identify the league's leading scorers
- Compare scoring outputs across top players
- Observe the gap between different scoring tiers
- Note how scoring leaders often correlate with MVP candidates and All-NBA selections

In [19]:
# Get top 15 scorers
top_scorers = players_df.sort_values('PTS', ascending=False).head(15)

# Create a bar chart with customized colors based on scoring volume
fig2 = px.bar(
    top_scorers,
    x='Player',
    y='PTS',
    color='PTS',  # Color bars by points
    color_continuous_scale='Viridis',  # Use a color scale
    hover_data=['Team', 'Position', 'G', 'MP', 'FG%', '3P%', 'FT%'],  # Additional data for hover
    title='Top 15 NBA Scorers (Points Per Game) - 2022-23 Season',
    labels={
        'Player': 'Player Name',
        'PTS': 'Points Per Game',
        'Team': 'Team',
        'G': 'Games Played',
        'MP': 'Minutes Per Game',
        'FG%': 'Field Goal %',
        '3P%': '3-Point %',
        'FT%': 'Free Throw %'
    },
    template='plotly_white'
)

# Customize the layout
fig2.update_layout(
    xaxis=dict(
        title_font=dict(size=14),
        tickfont=dict(size=10),
        tickangle=45,
        categoryorder='total descending'  # Order bars by value
    ),
    yaxis=dict(
        title_font=dict(size=14),
        tickfont=dict(size=12),
        showgrid=True,
        gridwidth=0.5,
        gridcolor='lightgray'
    ),
    coloraxis_colorbar=dict(
        title=dict(
            text='PPG',
            side='right',  # Position title to the right
            font=dict(size=12)
        ),
        thicknessmode="pixels",
        thickness=20,
        lenmode="pixels",
        len=300,
        tickfont=dict(size=10)
    ),
    title=dict(
        font=dict(size=16)
    ),
    margin=dict(l=40, r=40, t=50, b=100),
    height=600,
    width=900
)

fig2.show()

## Visualization 3: Player Performance by Position

This visualization compares statistical distributions (points, rebounds, and assists) across different positions using box plots. This helps identify how performance metrics vary by player role.

**Key Insights:**
- Guards typically excel in assists but have lower rebounding numbers
- Centers dominate rebounding but generally score and assist less
- Forwards tend to be more balanced across categories
- The box plots show not just averages but the full range and distribution of performances
- Outliers (stars who exceed positional norms) can be identified

The box plots display:
- The median (middle line)
- Interquartile range (box)
- Range of typical values (whiskers)
- Outliers (individual points)

In [21]:
# Create a box plot showing statistical distributions by position
fig3 = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=('Scoring by Position', 'Rebounding by Position', 'Assists by Position')
)

# Position colors
position_colors = {'Guard': 'blue', 'Forward': 'green', 'Center': 'red'}

# Add box plots for points, rebounds, and assists
positions = ['Guard', 'Forward', 'Center']

# Points boxplot
for i, position in enumerate(positions):
    position_data = players_df[players_df['Position_Simple'] == position]
    
    fig3.add_trace(
        go.Box(
            y=position_data['PTS'],
            name=position,
            marker_color=position_colors[position],
            boxmean=True  # Show mean as a dashed line
        ),
        row=1, col=1
    )

# Rebounds boxplot
for i, position in enumerate(positions):
    position_data = players_df[players_df['Position_Simple'] == position]
    
    fig3.add_trace(
        go.Box(
            y=position_data['TRB'],
            name=position,
            marker_color=position_colors[position],
            boxmean=True,
            showlegend=False
        ),
        row=1, col=2
    )

# Assists boxplot
for i, position in enumerate(positions):
    position_data = players_df[players_df['Position_Simple'] == position]
    
    fig3.add_trace(
        go.Box(
            y=position_data['AST'],
            name=position,
            marker_color=position_colors[position],
            boxmean=True,
            showlegend=False
        ),
        row=1, col=3
    )

# Update layout
fig3.update_layout(
    title_text='Statistical Performance by Position (2022-23 Season)',
    boxmode='group',
    height=500,
    width=1000,
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    font=dict(size=12)
)

# Update y-axis labels
fig3.update_yaxes(title_text='Points Per Game', row=1, col=1)
fig3.update_yaxes(title_text='Rebounds Per Game', row=1, col=2)
fig3.update_yaxes(title_text='Assists Per Game', row=1, col=3)

fig3.show()

## Results and Analysis

The dashboard visualizations provide several key insights into the 2022-23 NBA season:

### Team Performance Analysis
- **Milwaukee Bucks** and **Boston Celtics** stood out as the top teams in the Eastern Conference, combining strong offense with solid defense.
- The **Sacramento Kings** had one of the league's best offenses (120.7 PPG) but struggled defensively.
- **Cleveland Cavaliers** established themselves as an elite defensive team (106.9 PA/G).
- There's a clear correlation between point differential and win percentage, confirming the importance of both offensive and defensive efficiency.

### Top Scorers Analysis
- **Joel Embiid** led the league in scoring at 33.1 PPG, followed closely by **Luka Doncic** (32.4) and **Damian Lillard** (32.2).
- Among the top 10 scorers, **Nikola Jokic** had the highest field goal percentage (63.2%), demonstrating exceptional efficiency.
- Many of the top scorers are guards or forwards who handle the ball extensively, highlighting the perimeter-oriented nature of modern NBA offense.

### Positional Performance Analysis
- **Centers** have the widest distribution in rebounding, with some significantly outperforming others.
- **Guards** consistently lead in assists, with minimal overlap with centers.
- **Forwards** tend to be the most versatile, showing balanced distributions across all three statistical categories.
- Despite positional specialization, individual outliers demonstrate that elite players often transcend traditional positional limitations.

These insights help us understand the various factors that contribute to success in the modern NBA, from team construction to individual player performance.

## Summary and Future Directions

This NBA statistics dashboard provides a comprehensive analysis of team and player performance during the 2022-23 season. Through interactive visualizations, we've explored offensive and defensive team metrics, individual scoring leaders, and positional performance differences.

### Key Findings:
1. Team success correlates strongly with point differential, with the best teams excelling on both ends of the court
2. Top scorers come from various positions, but guards and forwards dominate the highest scoring tiers
3. Clear statistical patterns exist across positions, but exceptional players often break positional stereotypes

### Future Enhancements:
- **Time Series Analysis**: Track team and player performance across multiple seasons to identify trends
- **Advanced Metrics**: Incorporate more advanced statistics like True Shooting Percentage, Player Efficiency Rating, and Win Shares
- **Playoff Performance**: Compare regular season vs. playoff statistics to identify "clutch" performers
- **Lineup Analysis**: Evaluate the effectiveness of different player combinations
- **Shooting Distribution**: Analyze shot selection and efficiency from different court locations

This dashboard demonstrates the power of data visualization for understanding complex sports dynamics and could be expanded to include more sophisticated analyses in the future.

## Conclusion

The 2022-23 NBA season featured exceptional performances at both the team and individual level. The Milwaukee Bucks and Boston Celtics established themselves as the top regular-season teams, while players like Joel Embiid, Luka Doncic, and Damian Lillard delivered remarkable individual scoring performances.

Our analysis confirms several basketball principles while also highlighting interesting outliers. The data shows that while positions still matter in basketball, the lines between traditional roles continue to blur in the modern NBA, with versatile players increasingly valuable.

This dashboard serves as a foundation for deeper basketball analysis and can be expanded to incorporate additional metrics and dimensions in future iterations.